import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/app/components/Header";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='inter.className h-dvh bg-blue-300 flex justify-center flex-col'>
      {false ? <Header/> : null}
      <div className="h-full bg-amber-500 relative">
              {children}
      </div>
      </body>
    </html>
  )
}
